### Class exercise: table
![](http://127.0.0.1:8888/files/images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [8]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)

red = a[0, 1:4]  
blue = a[0::2, 4]  
light_blue  = a[:, 1::2] 
green = a[0:3, 2]
yellow = a[0,0]

print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\nlight_blue:',light_blue,'\nyellow:',yellow)

red: [11 12 13] 
blue: [14 24] 
green:
 [12 17 22] 
light_blue: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
yellow: 10


## 3D
#### reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](http://127.0.0.1:8888/notebooks/images/cube.png)

### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [15]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
#print('whole cube: \n',a, '\n---------------')

print('Slice out [12 13 14] : \n', a[1,1,:],'\n---------')
print('Slice out [3 12 21]: \n',a[:,1,0],'\n---------')
print('Slice out all y-values where x is 2 and z is 0: \n',a[0,:,2],'\n---------')

Slice out [12 13 14] : 
 [12 13 14] 
---------
Slice out [3 12 21]: 
 [ 3 12 21] 
---------
Slice out all y-values where x is 2 and z is 0: 
 [2 5 8] 
---------


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [8]:
import numpy as np
data = np.arange(1,101).reshape(10,10)

# Mask to return only even numbers
datab = data[data%2==0]
print(datab)

#Return only numbers that end with 6
datac = data[data%10 == 6]
print(datac)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 6 16 26 36 46 56 66 76 86 96]


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children of 0 years were there in Copenhagen in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [16]:
with open("../../../data/befkbhalderstatkode.csv") as f:
    data = f.readlines()
    
#lmaooo
    
    

['AAR,BYDEL,ALDER,STATKODE,PERSONER\n' '2015,1,0,5100,614\n'
 '2015,1,0,5104,2\n' ... '1992,99,89,5100,1\n' '1992,99,90,5180,1\n'
 '1992,99,93,5100,1\n']
