### Class exercise: table
![](http://127.0.0.1:8888/files/images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [8]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)

red = a[0, 1:4]  
blue = a[0::2, 4]  
light_blue  = a[:, 1::2] 
green = a[0:3, 2]
yellow = a[0,0]

print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\nlight_blue:',light_blue,'\nyellow:',yellow)

red: [11 12 13] 
blue: [14 24] 
green:
 [12 17 22] 
light_blue: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
yellow: 10


## 3D
#### reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](http://127.0.0.1:8888/notebooks/images/cube.png)

### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [15]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
#print('whole cube: \n',a, '\n---------------')

print('Slice out [12 13 14] : \n', a[1,1,:],'\n---------')
print('Slice out [3 12 21]: \n',a[:,1,0],'\n---------')
print('Slice out all y-values where x is 2 and z is 0: \n',a[0,:,2],'\n---------')

Slice out [12 13 14] : 
 [12 13 14] 
---------
Slice out [3 12 21]: 
 [ 3 12 21] 
---------
Slice out all y-values where x is 2 and z is 0: 
 [2 5 8] 
---------


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [ ]:
data = np.arange(1,101).reshape(10,10)
